### ISSUE TITLE
saveData and handleComboBox methods in CustomerController class

### ISSUE THREAD

**Issue by chelsnola** [M3f1st0/MiuZiKs_Official_V2#6]
Regarding this comment:

line 56: //don't know if we will be saving customers so this is left undeveloped for now

will the saveData method be removed or not?

**Comment by chelsnola** [comment]
line 79: //The ADD NEW RECORD functionality should be disabled in CustomerView

What needs to be done with this?

**Comment by M3f1st0** [comment]
Im not sure if we discussed that in a meeting or with Karolis, but we are not supposed to create new customers from the Administrators side, as we would have to choose username and password for that client, so we said that we would only be able to alter some customer information.

If that answers the question you may close the issue.
